---
version: '3.1'
services:
  mysql:
    image: mysql:5.7
    container_name: local_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
    ports:
      - 3306:3306

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: local_pma
#    links:
#      - mysql
#    environment:
#      PMA_HOST: mysql
#    restart: always
#    ports:
#      - 8183:80
